"""Synchronous Vectors client. Async counterpart is generated by tools/generate_async.py."""

from __future__ import annotations

import time
from collections.abc import Iterable, Iterator, Mapping, Sequence
from typing import Any

import httpx

from ._common import base_url, batches, decode, encode, segment
from ._version import __version__
from .errors import APIError, BulkInsertError, ProtocolError, TransportError
from .models import (
    CommandResult,
    IngestBatch,
    IngestSummary,
    QueryResult,
    parse_result,
    parse_results,
)


class Client:
    """Reuse one connection pool for SQL, vector search, and graph operations.

    base_url is the server root (without /v1). Redirects are disabled. Only
    provider-free reads retry explicit server overload responses; writes, SQL,
    and provider calls are never automatically replayed.
    """

    def __init__(
        self,
        url: str = "http://127.0.0.1:8080",
        *,
        token: str | None = None,
        timeout: float | httpx.Timeout = 30.0,
        max_connections: int = 20,
        max_retries: int = 2,
        transport: httpx.BaseTransport | None = None,
        trust_env: bool = False,
    ):
        if (
            isinstance(max_retries, bool)
            or not isinstance(max_retries, int)
            or not 0 <= max_retries <= 10
        ):
            raise ValueError("max_retries must be an integer between 0 and 10")
        if (
            isinstance(max_connections, bool)
            or not isinstance(max_connections, int)
            or max_connections < 1
        ):
            raise ValueError("max_connections must be a positive integer")
        headers = {
            "Accept": "application/json",
            "User-Agent": f"vectors-sdk/{__version__}",
        }
        if token:
            headers["Authorization"] = f"Bearer {token}"
        self._max_retries = max_retries
        self._http = httpx.Client(
            base_url=base_url(url),
            headers=headers,
            timeout=timeout,
            limits=httpx.Limits(
                max_connections=max_connections,
                max_keepalive_connections=max_connections,
            ),
            follow_redirects=False,
            transport=transport,
            trust_env=trust_env,
        )

    def __enter__(self) -> Client:
        return self

    def __exit__(self, *args: Any) -> None:
        self.close()

    def close(self) -> None:
        self._http.close()

    def _request(
        self,
        method: str,
        path: str,
        *,
        body: Any = None,
        content: bytes | None = None,
        params: dict[str, Any] | None = None,
        retry: bool = False,
    ) -> Any:
        payload = encode(body) if body is not None else content
        for attempt in range(self._max_retries + 1):
            try:
                response = self._http.request(
                    method,
                    path,
                    content=payload,
                    params=params,
                    headers={"Content-Type": "application/json"}
                    if payload is not None
                    else None,
                )
            except httpx.RequestError:
                raise TransportError(
                    "request failed or timed out; a submitted write may already have committed"
                ) from None
            try:
                return decode(response)
            except APIError as error:
                if (
                    not retry
                    or attempt == self._max_retries
                    or error.status_code != 503
                    or error.code != "overloaded"
                ):
                    raise
                delay = (
                    error.retry_after
                    if error.retry_after is not None
                    else 0.25 * 2**attempt
                )
                # Do not violate a long server Retry-After or block unboundedly.
                if delay > 30:
                    raise
                time.sleep(delay)
        raise AssertionError("unreachable")

    def health(self) -> dict[str, Any]:
        return self._request("GET", "healthz", retry=True)

    def readiness(self) -> dict[str, Any]:
        return self._request("GET", "readyz", retry=True)

    def settings(self) -> dict[str, Any]:
        return self._request("GET", "v1/settings/server", retry=True)

    def tables(self) -> dict[str, Any]:
        return self._request("GET", "v1/tables", retry=True)

    def schema(self, table: str) -> dict[str, Any]:
        return self._request("GET", f"v1/tables/{segment(table)}/schema", retry=True)

    def indexes(self, table: str) -> dict[str, Any]:
        return self._request("GET", f"v1/tables/{segment(table)}/indexes", retry=True)

    def relationships(self) -> dict[str, Any]:
        """List named scalar links and the revision required to change them."""
        return self._request("GET", "v1/relationships", retry=True)

    def create_relationship(
        self,
        name: str,
        *,
        source_table: str,
        source_column: str,
        target_table: str,
        target_column: str,
        expected_revision: int,
    ) -> dict[str, Any]:
        """Name a link between matching scalar fields and ensure both are indexed.

        Use the revision returned by relationships(). The server rejects stale
        revisions; writes are never retried. Definitions support ordinary SQL
        joins and do not enforce foreign keys or create graph chunk edges.
        """
        return self._request(
            "POST",
            "v1/relationships",
            body={
                "name": name,
                "source_table": source_table,
                "source_column": source_column,
                "target_table": target_table,
                "target_column": target_column,
                "expected_revision": expected_revision,
            },
        )

    def delete_relationship(
        self, name: str, *, expected_revision: int
    ) -> dict[str, Any]:
        """Remove a link definition while retaining records and scalar indexes."""
        return self._request(
            "DELETE",
            f"v1/relationships/{segment(name)}",
            body={"expected_revision": expected_revision},
        )

    def embedding_settings(self) -> dict[str, Any]:
        return self._request("GET", "v1/settings/embeddings", retry=True)

    def embed(
        self,
        texts: Sequence[str],
        *,
        input_type: str = "document",
        expected_settings: Mapping[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Generate vectors using server-side credentials; provider calls never retry."""
        body: dict[str, Any] = {"input": list(texts), "input_type": input_type}
        if expected_settings is not None:
            body["expected_settings"] = dict(expected_settings)
        return self._request("POST", "v1/embeddings", body=body)

    def execute(
        self, sql: str, parameters: Sequence[Any] | None = None
    ) -> list[QueryResult | CommandResult]:
        body: dict[str, Any] = {"sql": sql}
        if parameters is not None:
            body["parameters"] = list(parameters)
        return parse_results(self._request("POST", "v1/sql", body=body))

    def explain(
        self, sql: str, parameters: Sequence[Any] | None = None
    ) -> dict[str, Any]:
        body: dict[str, Any] = {"sql": sql}
        if parameters is not None:
            body["parameters"] = list(parameters)
        return self._request("POST", "v1/sql/intent", body=body, retry=True)

    def search(
        self,
        table: str,
        query: Sequence[float],
        *,
        vector_column: str = "embedding",
        metric: str = "cosine",
        select: Sequence[str] = (),
        filters: Sequence[Mapping[str, Any]] = (),
        limit: int = 10,
    ) -> QueryResult:
        result = parse_result(
            self._request(
                "POST",
                "v1/vector/search",
                body={
                    "table": table,
                    "vector_column": vector_column,
                    "query": list(query),
                    "metric": metric,
                    "select": list(select),
                    "filters": [dict(item) for item in filters],
                    "limit": limit,
                },
                retry=True,
            )
        )
        if not isinstance(result, QueryResult):
            raise ProtocolError("vector search did not return a query result")
        return result

    def iter_insert(
        self,
        table: str,
        rows: Iterable[Mapping[str, Any]],
        *,
        batch_size: int = 1000,
        max_batch_bytes: int = 4 * 1024 * 1024,
        normalize_vectors: bool = False,
        on_conflict: str = "fail",
        conflict_target: str | None = None,
        update_columns: Sequence[str] = (),
    ) -> Iterator[IngestBatch]:
        """Lazily insert bounded, individually atomic batches and yield progress.

        Tune batch_size/max_batch_bytes to settings()['limits']. Consuming only
        part of this iterator sends only those batches (with one row lookahead).
        """
        path = f"v1/tables/{segment(table)}/rows"
        options = {
            "normalize_vectors": normalize_vectors,
            "on_conflict": on_conflict,
            "conflict_target": conflict_target,
            "update_columns": list(update_columns),
        }
        offset = affected = completed = 0
        try:
            for content, count in batches(
                rows,
                batch_size=batch_size,
                max_batch_bytes=max_batch_bytes,
                options=options,
            ):
                result = parse_results(self._request("POST", path, content=content))
                if len(result) != 1 or not isinstance(result[0], CommandResult):
                    raise ProtocolError("insertion did not return one command result")
                batch = IngestBatch(offset, count, result[0].rows_affected)
                offset += count
                affected += batch.rows_affected
                completed += 1
                yield batch
        except Exception as error:
            raise BulkInsertError(offset, affected, completed, error) from error

    def insert(
        self, table: str, rows: Iterable[Mapping[str, Any]], **options: Any
    ) -> IngestSummary:
        input_rows = affected = count = 0
        for batch in self.iter_insert(table, rows, **options):
            input_rows += batch.row_count
            affected += batch.rows_affected
            count += 1
        return IngestSummary(input_rows, affected, count)

    def preview_chunks(
        self, text: str, *, title: str = "", chunking: Mapping[str, int] | None = None
    ) -> dict[str, Any]:
        body: dict[str, Any] = {"text": text, "title": title}
        if chunking is not None:
            body["chunking"] = dict(chunking)
        return self._request("POST", "v1/graph/chunk", body=body, retry=True)

    def collections(self) -> list[dict[str, Any]]:
        return self._request("GET", "v1/graph/collections", retry=True)

    def create_collection(
        self,
        name: str,
        *,
        document_columns: Sequence[Mapping[str, Any]] | None = None,
        semantic_neighbors: int = 3,
        semantic_threshold: float = 0.8,
    ) -> dict[str, Any]:
        """Create SQL-backed documents, chunks, and relationships with optional typed fields."""
        body: dict[str, Any] = {
            "name": name,
            "semantic_neighbors": semantic_neighbors,
            "semantic_threshold": semantic_threshold,
        }
        if document_columns is not None:
            body["document_columns"] = [dict(column) for column in document_columns]
        return self._request("POST", "v1/graph/collections", body=body)

    def collection(self, name: str) -> Collection:
        """Return a local handle; no network request or implicit creation."""
        return Collection(self, name)


class Collection:
    def __init__(self, client: Client, name: str):
        self._client = client
        self.name = name
        self._path = f"v1/graph/collections/{segment(name)}"

    def info(self) -> dict[str, Any]:
        return self._client._request("GET", self._path, retry=True)

    def ingest(
        self,
        document_id: str,
        text: str,
        *,
        title: str = "",
        source: str = "",
        metadata: Mapping[str, Any] | None = None,
        chunking: Mapping[str, int] | None = None,
        expected_revision: int | None = None,
    ) -> dict[str, Any]:
        body: dict[str, Any] = {
            "id": document_id,
            "text": text,
            "title": title,
            "source": source,
            "metadata": dict(metadata) if metadata is not None else {},
        }
        if chunking is not None:
            body["chunking"] = dict(chunking)
        if expected_revision is not None:
            body["expected_revision"] = expected_revision
        return self._client._request("POST", self._path + "/documents", body=body)

    def document(self, document_id: str) -> dict[str, Any]:
        return self._client._request(
            "GET", self._path + f"/documents/{segment(document_id)}", retry=True
        )

    def delete_document(
        self, document_id: str, *, expected_revision: int
    ) -> dict[str, Any]:
        return self._client._request(
            "DELETE",
            self._path + f"/documents/{segment(document_id)}",
            body={"expected_revision": expected_revision},
        )

    def search(
        self,
        text: str,
        *,
        seed_limit: int = 5,
        max_hops: int = 1,
        neighbor_limit: int = 8,
        max_results: int = 20,
    ) -> dict[str, Any]:
        return self._client._request(
            "POST",
            self._path + "/search",
            body={
                "text": text,
                "seed_limit": seed_limit,
                "max_hops": max_hops,
                "neighbor_limit": neighbor_limit,
                "max_results": max_results,
            },
        )

    def retrieve(
        self,
        text: str,
        *,
        candidate_limit: int = 40,
        seed_limit: int = 12,
        max_results: int = 10,
        max_hops: int = 1,
        neighbor_limit: int = 8,
        diversity: float = 0.3,
        max_context_bytes: int = 24000,
        max_per_document: int = 3,
        vector_weight: float = 1.0,
        lexical_weight: float = 1.0,
        reranker: str = "local",
        direction: str = "outgoing",
        kind: str | None = None,
        min_weight: float = 0.0,
        document_filters: Sequence[Mapping[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """Hybrid retrieval with citations and optional typed document filters.

        Filters combine with AND and use column/operator/value mappings. They
        constrain both vector candidates and graph expansion. This operation
        requires the collection's embedding provider and is never retried.
        """
        body: dict[str, Any] = {
            "text": text,
            "candidate_limit": candidate_limit,
            "seed_limit": seed_limit,
            "max_results": max_results,
            "max_hops": max_hops,
            "neighbor_limit": neighbor_limit,
            "diversity": diversity,
            "max_context_bytes": max_context_bytes,
            "max_per_document": max_per_document,
            "vector_weight": vector_weight,
            "lexical_weight": lexical_weight,
            "reranker": reranker,
        }
        # Preserve the original payload for callers using the default traversal.
        if direction != "outgoing":
            body["direction"] = direction
        if kind is not None:
            body["kind"] = kind
        if min_weight != 0.0:
            body["min_weight"] = min_weight
        if document_filters is not None:
            body["document_filters"] = [dict(item) for item in document_filters]
        return self._client._request(
            "POST",
            self._path + "/retrieve",
            body=body,
        )

    def browse(
        self,
        *,
        document_id: str | None = None,
        offset: int = 0,
        limit: int = 100,
        max_edges: int = 500,
    ) -> dict[str, Any]:
        params: dict[str, Any] = {
            "offset": offset,
            "limit": limit,
            "max_edges": max_edges,
        }
        if document_id is not None:
            params["document_id"] = document_id
        return self._client._request(
            "GET", self._path + "/graph", params=params, retry=True
        )

    def neighborhood(
        self,
        chunk_id: str,
        *,
        max_hops: int = 1,
        neighbor_limit: int = 8,
        max_nodes: int = 100,
        max_edges: int = 500,
        direction: str = "both",
        kind: str | None = None,
        min_weight: float = 0.0,
    ) -> dict[str, Any]:
        params: dict[str, Any] = {
            "chunk_id": chunk_id,
            "max_hops": max_hops,
            "neighbor_limit": neighbor_limit,
            "max_nodes": max_nodes,
            "max_edges": max_edges,
            "direction": direction,
            "min_weight": min_weight,
        }
        if kind is not None:
            params["kind"] = kind
        return self._client._request(
            "GET", self._path + "/neighborhood", params=params, retry=True
        )

    def upsert_relationship(
        self,
        from_chunk: str,
        to_chunk: str,
        kind: str,
        *,
        weight: float,
        expected_revision: int,
    ) -> dict[str, Any]:
        return self._client._request(
            "POST",
            self._path + "/relationships",
            body={
                "from_chunk": from_chunk,
                "to_chunk": to_chunk,
                "kind": kind,
                "weight": weight,
                "expected_revision": expected_revision,
            },
        )

    def delete_relationship(
        self, from_chunk: str, to_chunk: str, kind: str, *, expected_revision: int
    ) -> dict[str, Any]:
        return self._client._request(
            "DELETE",
            self._path + "/relationships",
            body={
                "from_chunk": from_chunk,
                "to_chunk": to_chunk,
                "kind": kind,
                "expected_revision": expected_revision,
            },
        )
