"""Keep explicit, inspectable async signatures in sync with the sync client."""

from pathlib import Path
import re
import sys

root = Path(__file__).resolve().parents[1] / "src" / "vectors_sdk"
source = (root / "_client.py").read_text()
source = source.replace(
    source.splitlines()[0],
    '"""Async Vectors client. Generated by tools/generate_async.py; edit _client.py."""',
)
source = source.replace("import time", "import asyncio")
source = re.sub(r"\bClient\b", "AsyncClient", source)
source = re.sub(r"\bCollection\b", "AsyncCollection", source)
source = source.replace("httpx.BaseTransport", "httpx.AsyncBaseTransport")
source = re.sub(r"\bIterator\b", "AsyncIterator", source)
source = re.sub(r"    def (?!__init__\b|collection\b)", "    async def ", source)
source = source.replace("__enter__", "__aenter__").replace("__exit__", "__aexit__")
source = source.replace("def close(", "def aclose(")
source = source.replace("self.close()", "await self.aclose()")
source = source.replace("self._http.close()", "await self._http.aclose()")
source = source.replace("self._http.request(", "await self._http.request(")
source = source.replace("self._request(", "await self._request(")
source = source.replace("self._client._request(", "await self._client._request(")
source = source.replace("time.sleep(delay)", "await asyncio.sleep(delay)")
source = source.replace(
    "for batch in self.iter_insert(", "async for batch in self.iter_insert("
)
target = root / "_async_client.py"
if "--check" in sys.argv:
    if not target.exists() or target.read_text() != source:
        raise SystemExit("async client differs; run python tools/generate_async.py")
else:
    target.write_text(source)
